avatar:
  size: 50
  large_size: 100
session:
  remember_value: "1"
role:
  admin: "admin"
  supervisor: "supervisor"
  trainee: "trainee"
subject_course:
  status_start: 1
  status_finish: 2
pagination:
  size: 15
status:
  pending: 0
  pending_text: "pending"
  started: 1
  started_text: "started"
  finished: 2
  finished_text: "finished"
  active: true
  inactive: false
activity:
  target_type:
    course: 0
    subject: 1
    task: 2
  content:
    start_subject: "activity.content.start_subject"
    finished_subject: "activity.content.finished_subject"
    start_course: "activity.content.start_course"
    finished_course: "activity.content.finished_course"
    completed_task: "activity.content.completed_task"
    joined_course: "activity.content.joined_course"
    joined_subject: "activity.content.joined_subject"
